<a href="https://colab.research.google.com/github/mkdirlife/orm/blob/main/%EB%AA%A8%EB%91%90%EC%9D%98%EC%97%B0%EA%B5%AC%EC%86%8C_4%EC%A3%BC%EC%B0%A8_5%EC%9D%BC_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 풀이1
def solution(url):
    return url.split('@')[0] + '@weniv.co.kr'

solution('kim123@gmail.com')

'kim123@weniv.co.kr'

In [ ]:
# 변경된 문제의 답
# 문제: 주어진 문자열에서 모든 이메일 주소를 user@weniv.co.kr으로 변경하시오.

# 예시 입력: "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
# 예시 출력: "저의 이메일 주소는 kim123@weniv.co.kr입니다. 친구의 이메일 주소는 lee456@weniv.co.kr입니다."

import re

def changedomain(url):
    return url.split('@')[0] + '@weniv.co.kr'

findpattern = re.findall(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}" ,
                            "저의 이메일 주소는 kim123@gmail.com입니다. "
                            "친구의 이메일 주소는 lee456@gmail.com입니다.")

url = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."

for url in findpattern:
    print(changedomain(url))

kim123@weniv.co.kr
lee456@weniv.co.kr


In [ ]:

# 변경된 문제의 해답
my_string = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
re.sub(r"@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}", "@weniv.co.kr", my_string)

'저의 이메일 주소는 kim123@weniv.co.kr입니다. 친구의 이메일 주소는 lee456@weniv.co.kr입니다.'

In [ ]:
import re   # import 와 코드는 보통 2칸


def hello():
    print('world')

def solution(data):
    return

solution("")

In [ ]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120824

# 코딩인터뷰 완전분석 에서 말하는 방법
# 듣기
# 예제
# 무식하게 풀기
# 최적화
# 검토하기
# 구현하기
# 테스트
def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]

    # filter(lambda x: x % 2 != 0, data)
    return [sum(짝수), sum(홀수)]

solution([1, 2, 3, 4, 5])

[2, 3]

In [1]:
# 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120824

# 1번
data = [1, 2, 3, 4, 5]

def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]

    return [sum(짝수), sum(홀수)]

solution(data)



[2, 3]

In [ ]:

# 2번
def solution(data):
    count = 0
    for i in data:
        if i % 2 == 0:
            count += 1
    return [count, len(data)-count]

solution([1, 2, 3, 4, 5])

[2, 3]

In [3]:
# 3번
data = [1, 2, 3, 4, 5]

def solution(num_list):
    answer = [0, 0]
    for i in num_list:
        answer[i % 2] += 1
    return answer

solution(data)

[2, 3]

In [2]:
def solution(data):
    return sum(map(lambda x: x % 2 != 0, data))

solution([1, 2, 3, 4, 5])

3

In [ ]:
# 좋은 풀이는 아닙니다.
# 4번
def solution(data):
    짝수 = [i % 2 == 0 for i in data]

    return [sum(짝수), len(data) - sum(짝수)]   # sum이 순회합니다.
solution([1, 2, 3, 4, 5])

In [ ]:
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    개수 = sum(짝수)
    return [sum(짝수), len(data) - 개수]   # sum이 순회합니다.
solution([1, 2, 3, 4, 5])

[2, 3]

## 머쓱이보다 키 큰 사람
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120585

In [5]:

#           입 력                  출력
# [149, 180, 192, 170]  167         3
# [180, 120, 140]       190	        0

data = [149, 180, 192, 170]
n = 167

def solution(array, height):
    answer = 0
    for i in array:
        if i > height:
            answer += 1
    return answer

solution(data, n)


3

In [ ]:
# filter 는 len이 없습니다.
# len 이 없는 이유? fliter는 순회 돌기 전까지 실행이 되지 않은 함수
# for와 같이 순회를 돌아야 그때서야 각 원소 별로 접근해서
def solution(array, height):
    return len(list(filter(lambda x: x > height, array)))
    # return list[filter(lambda x: x > height, array)]

solution([149, 180, 192, 170], 167)

3

In [6]:
def solution(array, height):
    return sum(map(lambda x: x > height, array))
    # return list[filter(lambda x: x > height, array)]

solution([149, 180, 192, 170], 167)

3

In [ ]:
def solution(array, height):
    return sum(i > height for i in array)
    # return list[filter(lambda x: x > height, array)]

solution([149, 180, 192, 170], 167)

3

## 숨어있는 숫자의 덧셈
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120851

In [ ]:
def solution(my_string):
    answer = 0
    for i in my_string:
        if i.isdigit():
            answer += int(i)
    return answer

solution("aAb1B2cC34oOp")

10

In [7]:
# r은 raw 날것의 라는 뜻이 있어요.
# 실무에서 자주쓰는 용어입니다. raw != low(이 용어는 자주 사용하지 않습니다.)
# raw data를 전달해줘 => 가공하지 않은 순수 데이터를 달라는 얘기입니다.

r'hello\nworld' # \n은 이스케이프 문자입니다.
print('hello\nworld')
print(r'hello\nworld') # 왜? 정규표현식에서 이스케이프 문자를 많이 사용하니까요.


import re

# re.findall(r'[0-9]', "aAb1B2cC34oOp")

def solution(my_string):
    return sum(map(int, re.findall(r'[0-9]', my_string)))
    #return sum(map(int, re.sub(r'[a-zA-Z]', '', my_string)))
solution("aAb1B2cC34oOp")

hello
world
hello\nworld


10

In [ ]:
def solution(my_string):
    # return list(filter(lambda x: x.isdigit(), list(my_string)))
    # return list(filter(str.isdigit, list(my_string)))
    # return list(filter(lambda x: x.isdigit(), my_string))
    return list(filter(str.isdigit, my_string)) # isdigit은 str 클래스에서 제공하는 함수
solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [ ]:
# isdigit에 () 가 있고 없고의 차이는?
def 함수(x):
    return x.isdigit()

def solution(my_string):
    return list(filter(함수, my_string))
solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [ ]:
def solution(my_string):
    return sum(map(int, filter(str.isdigit, my_string))) # isdigit은 str 클래스에서 제공하는 함수
solution("aAb1B2cC34oOp")

10

In [ ]:
def solution(my_string):
    return sum(map(lambda x: int(x) if x.isdigit() else False, my_string)) # isdigit은 str 클래스에서 제공하는 함수
solution("aAb1B2cC34oOp")

10

# 암호 해독
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120892

In [9]:
def solution(cipher, code):
    return cipher[code-1::code]

solution("dfjardstddetckdaccccdegk", 4)

'drdccd'

In [8]:
def solution(cipher, code):
    count = 1
    answer = ''
    for i in cipher:
        if count == code:
            count = 0
            answer += i
        count += 1
    return answer

solution("dfjardstddetckdaccccdegk", 4)

'attack'

In [ ]:
def solution(cipher, code):
    answer = ''
    for i, j in enumerate(cipher, 1):
            #print(i, j)
        if i % code == 0:
            answer += j
    return answer

solution("dfjardstddetckdaccccdegk", 4)

'attack'

In [ ]:
def solution(cipher, code):
    answer = ''
    for i in range(1, len(cipher) // code + 1):
        answer += cipher[i * code - 1]
    print(answer)
    return answer

solution("dfjardstddetckdaccccdegk", 4)

attack


'attack'

# 369 게임
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120891

In [ ]:
import re

def solution(order):
    answer = 0
    order = str(order)
    answer = len((list(re.findall(r'[369]', order))))
    return answer

solution(29423)

2

In [ ]:
def solution(order):
    order = str(order)
    return order.count('3') + order.count('6') + order.count('9')

# 중복문자 제거
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120888

In [10]:
def solution(my_string):
    answer = ''
    for i in my_string:
        if i not in answer:
            answer += i
    return answer

solution("We are the world")

'We arthwold'

In [11]:
def solution(my_string):
    return ''.join(dict.fromkeys(my_string)) # 딕셔너리는 키의 중복이 안된다는 점을 이용! dict는 이제 순서를 보장합니다!

solution("We are the world")

'We arthwold'

In [ ]:
''.join(['hello', 'world', '!'])
''.join({'hello', 'world', '!'})
''.join({'one': 10, 'two': 20}) # 왜 결과가 이렇죠? dict을 for문을 돌았을때 key만 나오는 이유와 같습니다.

'onetwo'

In [ ]:
str.isdigit
dict.fromkeys('hello')
dict.fromkeys('abccba')

{'a': None, 'b': None, 'c': None}

## A로 B 만들기
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120886

In [ ]:
def solution(before, after):
    answer = 0
    if len(before) != len(after):
        return 0

    if before[::-1] == after:
        answer = 1

    return answer

solution("olleh", "hello")
#solution("allpe", "apple")

1

In [ ]:
def solution(before, after):
    answer = 0

    if sorted(before) == sorted(after):
        answer = 1

    return answer

solution("olleh", "hello")
#solution("allpe", "apple")

1

In [12]:
import collections

def solution(before, after):
    answer = 0
    print(collections.Counter(before))

    if collections.Counter(before) == collections.Counter(after):
        answer = 1

    return answer

solution("olleh", "hello")
#solution("allpe", "apple")

Counter({'l': 2, 'o': 1, 'e': 1, 'h': 1})


1

In [ ]:
def solution(before, after):
    answer = 0

    a = list(after)
    for i in before:
        if i in a:
            a.remove(i)
        else:
            return 0

    if a:
        return 0
    return 1

solution("olleh", "hello")
#solution("allpe", "apple")

1

In [ ]:
# 회문
# 왼쪽으로 밀기 'hello' => 'elloh' => 'llohe'
# 오른쪽으로 밀기 'hello' => 'ohell' => 'lohel'
# collections.deque 를 사용해서 풀면 쉽게 풀립니다.

# 문제1 'hello'를 앞뒤로 이동시켜 'llohe'를 만들 수 있나요?
# 'hellohello' 여기 안에 있으면 됨.

# 문제2 몇칸 이동했나요?
# 'hellohello'.index('llohe') 여기서 인덱스 찾아오면 됨.

## 저주의 숫자3
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120871

In [ ]:
# 십진수    3숫자마을
# 1         1
# 2         2
# 3         4
# 4         5
# 5         7
# 6         8
# 7         10
# 8         11
# 9         14
# 10        16

def solution(n):
    answer= list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(100)))[n-1]
    return answer

solution(15)

25

In [ ]:
def solution(n):
    answer= lambda n: [i for i in range(1000) if i % 3 != 0 and '3' not in str(i)][n-1]
    return answer

solution(15)

<function __main__.solution.<locals>.<lambda>(n)>

In [ ]:
def solution(num):
    l = []
    for i in range(10):
        if i % 3 != 0:
            l.append(i)
        elif '3' not in str(i):
            l.append(i)
    return l

solution(15)



[0, 1, 2, 4, 5, 6, 7, 8, 9]

## 진료 순서 정하기
링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120835

In [ ]:
def solution(emergency):
    sorted_emergency = sorted(emergency, reverse = True)
    return [sorted_emergency.index(i)+1 for i in emergency]

solution([30, 10, 23, 6, 100])

[2, 4, 3, 5, 1]

In [ ]:
emergency = [30, 10, 23, 6, 100]
sorted_emergency = sorted(emergency, reverse = True)
sorted_emergency

[sorted_emergency.index(i)+1 for i in emergency]

In [ ]:
data = ['제주', '경기', '전주'] # ['064', '031', '063']
data2 = {
    '제주': '064',
    '경기': '031',
    '전주': '063'
}

[data2[i] for i in data]

['064', '031', '063']

## 가까운 수
링크: https://school.programmers.co.kr/learn/courses/30/lessons/120890

In [ ]:
def solution(array, n):
    answer = sorted(array, key=lambda x:(abs(x-n), x))[0]
    return answer

solution([3, 10, 28], 20)

28

In [ ]:
s = [3, 10, 28, 12]
sorted(s, key=lambda x:abs(x-20))[0]

28

In [ ]:
array = [3, 10, 28, 30, 12, 22, 18]
n = 20
sorted(array, key=lambda x:(abs(x-n), x))   # 팁, n-x이거나 x-n 2개 중에 하나입니다.

[18, 22, 12, 28, 10, 30, 3]

## k의 개수

링크: https://school.programmers.co.kr/learn/courses/30/lessons/120887

In [ ]:
# i	    j	k	result
# 1	    13	1	6
# 10    50	5	5
# 3	    10	2	0



def solution(i, j, k):
    answer = 0
    return answer



i = 1
j = 13
k = 1

str(list(range(i, j+1)))
'[1, 11, 13]'.count('1')

str(list(range(i, j+1))).count(str(k))

6

In [ ]:
a = 10
b = 20

# swap

temp = a
a = b
b = temp

# python에서 사용하는 swap

a = 10
b = 20
a, b = b, a
a, b

In [ ]:
i = 1
j = 13
k = 1

count = 0
for temp in range(i, j):
    print(str(temp).count(str(k)))
    count += str(temp).count(str(k))


1
0
0
0
0
0
0
0
0
1
2
1


In [ ]:
def solution(i, j, k):
    return str(list(range(i, j+1))).count(str(k))

## 직접 출제 문제

In [ ]:
# 각 선분이 있는 곳에 총 길이 합을 구하라
# [[0, 5], [3, 5], [7, 10]]

선 = [False] * 10
선

for i in range(0, 5):
    선[i] = True
선

for i in range(3, 5):
    선[i] = True
선

for i in range(7, 10):
    선[i] = True
선

sum(선)

8

In [ ]:
# 에라토스테네스의 체 => 소소판별 => 이것을 알고리즘 문제로 내는 것은 저는 반대
# # https://nahwasa.com/entry/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98-%EC%B2%B4-%ED%98%B9%EC%9D%80-%EC%86%8C%EC%88%98%ED%8C%90%EC%A0%95-%EC%8B%9C-%EC%A0%9C%EA%B3%B1%EA%B7%BC-%EA%B9%8C%EC%A7%80%EB%A7%8C-%ED%99%95%EC%9D%B8%ED%95%98%EB%A9%B4-%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

# 곱해지는 각 자연수중 하나는 무조건
# 제곱근과 같거나 작아야하는거니까

# 4 * 4
# 2 * 8

# 2, 3, 4

# 2, 4, 6, 8, 10, 12
# 3, 6, 9, 12
# ---
# 5, 10, 15

소수 = [True] * 120
소수[0] = 소수[1] = False

for i in range(4, 120, 2):
    소수[i] = False

for i in range(6, 120, 3):
    소수[i] = False

# for i in range(4, 120, 4)


for i in range(5, 120, 5):
    소수[i] = False

for 소수, 판별 in enumerate(소수):
    if 판별:
        print(소수)

2
3
7
11
13
17
19
23
29
31
37
41
43
47
49
53
59
61
67
71
73
77
79
83
89
91
97
101
103
107
109
113
119


In [ ]:
# 이렇게 쓰는게 가능합니다.^^
a = 10;b = 10
a, b

(10, 10)

In [ ]:

s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
sum(s, [])

[1, 3, 5, 7, 9, 11, 13, 15, 17]

In [ ]:
s = [[[1, 3, 5], [7, 9, 11]], [13, 15, 17]]
sum(s, [])

[[1, 3, 5], [7, 9, 11], 13, 15, 17]

In [ ]:
# 행렬의 연산과 같은 것은 np를 사용하시면 쉽고 빠르게 풀 수 있습니다.
import numpy as np

x = np.array([1, 2, 3])
x * 2

array([2, 4, 6])

In [ ]:

s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
s = np.array(s)
행, 렬 = np.where(s == 7)
행

print(cols, rows)

[1] [0]


In [ ]:
# 지뢰찾기
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
np.where(x == 1)


(array([0, 1, 2]), array([1, 1, 3]))

In [ ]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

s = 0
for i in x:
    s += i.count(1)

s

3

In [ ]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
x == 1

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [ ]:
x = [[0, 5, 2, 0],
     [0, 7, 0, 6],
     [0, 1, 3, 5]]

x = np.array(x)
x > 3

array([[False,  True, False, False],
       [False,  True, False,  True],
       [False, False, False,  True]])