<a href="https://colab.research.google.com/github/mkdirlife/orm/blob/main/%EC%98%A4%EB%A6%84%EC%BA%A0%ED%94%84_2%EC%A3%BC%EC%B0%A8_3%EC%9D%BC_%EC%8B%9C%ED%80%80%EC%8A%A4%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 시퀀스 자료형

In [ ]:
# 1.1 인덱싱
      #(-1)54321
          #01234
example = 'abcde'

print(example[0]) # 출력 : a
print(example[2]) # 출력 : c
print(example[-3]) # 출력 : c


a
c
c


In [ ]:
# 1.2 슬라이싱
      #(-1)54321
          #01234
example = 'abcde'

print(example[1:3])   # 출력: bc
print(example[-4:-1]) # 출력: bcd

range(10)[3] # 출력: 3
range(100)[::5] # 출력: range(0, 100, 5)

bc
bcd


range(0, 100, 5)

In [ ]:
# 1.3 특정항목 포함 여부

example = "abcde"
print('a' in example) # 출력: True
print('z' not in example) # 출력: False

True
False


In [ ]:
# 1.4 연결 & 반복

example1 = 'abcde'
example2 = 'f'
print(example1 + example2) # 출력: abcdef
print(example2 * 3)        # 출력: fff

abcdef
fff


In [ ]:
# 1.5 내장함수 사용

example = 'abcde'
print(len(example))  # 출력: 5
print(min(example))  # 출력: a
print(max(example))  # 출력: e

5
a
e


# 2. 시퀀스 자료형의 패킹과 언패킹

In [ ]:
# 2.1 튜플 패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)  # 출력: (1, 2, 3, 4)
type(packed_tuple)

(1, 2, 3, 4)


tuple

In [ ]:
tuple_example = 1
print(tuple_example)
type(tuple_example)

1


int

In [ ]:
# 2.2 언패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)
print(type(packed_tuple))

# 튜플 언패킹
a, b, c, d = packed_tuple
print(a)  # 출력: 1
print(b)  # 출력: 2
print(c)  # 출력: 3
print(d)  # 출력: 4

print(type(a))
print(type(b))
print(type(c))
print(type(d))

(1, 2, 3, 4)
<class 'tuple'>
1
2
3
4
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [ ]:
# 다양한 패킹/언패킹
# range는 0부터 n-1까지 숫자를 생성하는 함수

a, b, c = range(3)
print(range(3))
print(a, b, c)

range(0, 3)
0 1 2


In [ ]:
a, b, c, d, e = 'hello'

print(a)
print(b)
print(c)
print(d)
print(e)


h
e
l
l
o


In [ ]:
a, b = [10, 20]

print(a)
print(b)

10
20


In [ ]:
# 별표를 이용한 언패킹

first, *middle, last = [1, 2, 3, 4, 5, 6, 7]

print(first)
print(middle)
print(last)

print(type(first))
print(type(middle))
print(type(last))

1
[2, 3, 4, 5, 6]
7
<class 'int'>
<class 'list'>
<class 'int'>


# 2. 리스트

In [ ]:
# 리스트의 필요성

x1 = 100
x2 = 200
x3 = 300

x = [100, 200, 300]

In [ ]:
# 리스트의 장점 : 여러가지 자료형을 넣을 수 있다.

#z = [1, 'apple', 2.5, ['a', 'b'], (1, 2)]
z = [
		1,
		'apple',
		2.5,
		['a', 'b'],
		(1, 2), # 마지막에 컴마 넣어도 상관 없음
]
print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])



1
apple
2.5
['a', 'b']
(1, 2)


In [ ]:
# 2.2 리스트 값 수정

a = [1, 2, 3, 4, 5]
print(a)


a[0] = 10000
a[1] = [1, 2, 3, [4]]
print(a)


[1, 2, 3, 4, 5]
[10000, [1, 2, 3, [4]], 3, 4, 5]


In [ ]:
# 문자열은 변경할 수 없다.

s = 'licat'
print(s[0])
s[0] = 'k'

l


TypeError: ignored

In [ ]:
# 3. 리스트 안에 리스트

b = [[10, 20, 30], [1, 2, 3]]

print(b)
print(b[1][2]) # 출력: 3

[[10, 20, 30], [1, 2, 3]]
3


In [ ]:
print(b[1])

[1, 2, 3]


In [ ]:
# 리스트의 덧셈

a = [1, 2, 3, 4, 5]
b = [6, 7, 8]

print(a + b) # 출력: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
import numpy as np

l = [1, 2, 3]
ll = np.array(l)

print(type(l))
print(l)
print(l * 3)
print(l + l)

print(type(ll))
print(ll)
print(ll * 3)
print(ll + ll)

# 너무 당연하게 요소를 붙이는 것이다라고 생각하지 않으셨으면 좋겠습니다.

<class 'list'>
[1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]
[3 6 9]
[2 4 6]


In [ ]:
lst = [1, 2, 3, 4, 5]
print(lst[10])

IndexError: ignored

In [ ]:
# 슬라이싱 실습!

l = [1, 2, 3, 4, 5]
print(l[0:-1])     # 출력: [1, 2, 3, 4, 5]

[1, 2, 3, 4]


In [ ]:
print(l[::-1])  # 출력: [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


In [ ]:
print(l[::2])   # 출력: [1, 3, 5]

[1, 3, 5]


In [ ]:
print(l[1:4][::-1]) # 출력: [4, 3, 2, 1]

[4, 3, 2]


In [ ]:
# 데이터가 크다. 내가 원하는대로 데이터를 추출하고 싶다.

In [ ]:
# 1. 샘플링 -> 1억개 데이터 -> 천개! 정도 추출 -> 리스트 슬라이싱! 메서드! -> 1억개 데이터!

In [ ]:
l = [1, 2, 3, 4, 5]
print(l[10:20]) # 출력: []

[]
